name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment:
      name: Development
      url: https://github.com
    steps:
      - name: deploy
        run: echo I am deploying
